### ISSUE TITLE
High CPU usage when touching many objects at the same time

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#108]
### Steps to reproduce

* Create a number of small interactable cubes
* Make the interactor avatar object large enough to touch multiple cubes at the same time
* Touch multiple cubes

### Expected behavior

The CPU usage should not heavily spike

### Current behavior

The CPU usage spikes due to the `Trigger Stay` code running every frame to determine the nearest cube

### Notes

This can be mitigated slightly using the delay property on the Collision Tracker to prevent the trigger stay running every frame.

**Comment by thestonefox** [comment]
Notes from Discord:

i guess on collision enter you could add the object to a list, and on collision exit remove the item from the list

then when you perform a grab action (or other button action) process that list

and perhaps to do the currently touching, you'd process that list when the property was called

although i think that's not going to work for the touching events because now you only know the new touching item on an event such as you press a grab button, or you call a specific property, so you can't be notified via an event when the touching object changes, because you wont know it has changed until you ask

**Comment by thestonefox** [comment]
With no Stay Delay Interval, the FPS drops drastically

![slow](https://user-images.githubusercontent.com/1029673/153286134-624a4a95-fe5b-4ca8-8865-c82d8bc84749.gif)

With a Stay Delay Interval of 0.1, the FPS drop is much better but still drops by about 30fps

![better](https://user-images.githubusercontent.com/1029673/153286384-608f21a4-a1d0-4d6f-83e2-92be28a1a5b8.gif)

**Comment by thestonefox** [comment]
With the Grab Precognition on the Interactor Facade set to 0

and the Collision Tracker set so the Collision Changed does not do anything, and instead on the Collision Started and Collision Stopped it also calls `ProcessContentsChanged`

![image](https://user-images.githubusercontent.com/1029673/153287598-687dc0d5-f3ef-47dd-858d-26762f0b793d.png)

the FPS hardly drops at all

![nostay](https://user-images.githubusercontent.com/1029673/153287554-06b7db6a-bda1-4441-8092-234524cbef07.gif)
l

**Comment by thestonefox** [comment]
Increasing the Stay Delay Interval further to 0.25 improves matters more, but the grab precognition needs to be set at either 0 or higher than the stay delay interval for it to function correctly (e.g. 0.251 for the grab precognition setting)

![faster](https://user-images.githubusercontent.com/1029673/153288268-223eba51-5885-4f7e-b445-c3f7dd4acf33.gif)

**Comment by louspawn** [comment]
In addition to the previous comments, when the objects are even more (20+) there is performance drop even for the OnEnter and OnExit events not only for the OnStay. For example if you have very thin objects stacked on top of each other, like cards. 

The problem I think is that, the way it works right now, the nearest process runs for every hovering interactable which is inefficient and unnecessary. Also there are many objects created as local variables of functions that run throughout the process, adding extra work to the garbage collection, something that affects performance as well.

What I did to solve the issue and it works very good is created two custom scripts, one to handle the Collisions determining which objects are currently being touched and another to find the closest and call the appropriate events. The fact that there is only one place that the target acquisition is being managed, with no extra object creation and no unnecessary calculations, gives a huge boost on performance.

You can find my approach on the [gist I made](https://gist.github.com/louspawn/7dba98000f697de0c9516b126c3db748). I must warn you it is dirty and hacky (use it at your own risk!), but I hope it will help solving temporarily the problem and provide inspiration for future changes.

**Comment by thestonefox** [comment]
I'm a bit confused by the `InteractorCollisionManager` it seems on the face of it to be calculating the nearest touching object every Update, LateUpdate and FixedUpdate via a custom loop, and then calls OnActiveChange which goes through the same normal process as it does now.

The processing every unity moment isn't going to be that efficient, and I'm not sure how it would be more efficient than just processing in the `OnEnter` and `OnExit`.

I'm trying to decipher the logic, but what it looks like i can see is perhaps it only does the full "you've touched something new" when it knows the new touched object has actually changed.

So I wonder if the `OnStay` stuff can stay and the `NearestSorter` can stay, as you're doing that logic basically every physics frame anyway, so perhaps the slowdown is being caused by the Interactor messages to the Interactables.

So, I wonder if a logic block after the nearest sorter has run to check if the object has changed, if it hasn't changed then don't bother with the rest of the process.

**Comment by louspawn** [comment]
> I'm a bit confused by the `InteractorCollisionManager` it seems on the face of it to be calculating the nearest touching object every Update, LateUpdate and FixedUpdate via a custom loop, and then calls OnActiveChange which goes through the same normal process as it does now.

I would be surprised if you wouldn't be confused :) Yes this is what it is doing, but with bypassing whatever the CollisionTracker is doing. The reason I did it this way is to avoid the performance impact of the CollisionTracker, making sure also that it doesn't break the rest of the logic and current functionality. At least that's the idea.

> The processing every unity moment isn't going to be that efficient, and I'm not sure how it would be more efficient than just processing in the `OnEnter` and `OnExit`.

It is not exactly every unity moment, it is every unity moment that the interactor is touching an Interactable. It is iterating through the currently touching objects, but only if the dictionary is populated. So I believe it is the minimum required and the difference in the performance supports this claim.

> I'm trying to decipher the logic, but what it looks like i can see is perhaps it only does the full "you've touched something new" when it knows the new touched object has actually changed.

Yes that's exactly right.

> So I wonder if the `OnStay` stuff can stay and the `NearestSorter` can stay, as you're doing that logic basically every physics frame anyway, so perhaps the slowdown is being caused by the Interactor messages to the Interactables.

I am not familiar with the messages you mention here, so I cannot comment on that.

> So, I wonder if a logic block after the nearest sorter has run to check if the object has changed, if it hasn't changed then don't bother with the rest of the process.

This sounds about right to me I think.

**Comment by thestonefox** [comment]
Pull request with outlined fixes

https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/pull/110
