### ISSUE TITLE
Interactable: Method or Property to get the precision grab created transform/gameobject

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#117]
When we use Grab Follow Action, and choose Precision Grab (or Forced Precision Grab), it will create a temp locator object.
![image](https://user-images.githubusercontent.com/22952143/166437850-dc7296eb-90ca-46c7-a9b4-8eb05f3e84c2.png)

I would like to retreive this from the `Interactor.Grabbed(InteractableFacade interactable)` event.

i can only trace to
``` 
var followAction = interactable.Configuration.GrabConfiguration.PrimaryAction as Tilia.Interactions.Interactables.Interactables.Grab.Action.GrabInteractableFollowAction;
GameObject precisionCreateContainer = followAction.PrecisionCreateContainer;
// ..... ???
```
that created object is initially parented to this container, but whenever the grab happens, it is parented to somewhere else.
I am not sure how to get a reference from there onwards.

**Comment by thestonefox** [comment]
Ok so the way it works (i think) is......

When you grab something with the precision point, it needs to create an offset point of the controller that is grabbing it.

So the `[Zinnia][CollisionPointContainer][<yourname>]` is created as a child of the `Interactable` which is then used as a target offset for the follow logic `FollowModifier`

![image](https://user-images.githubusercontent.com/1029673/166441662-846fbebd-f338-4ea8-a061-f535d09414f4.png)


So it could be accessed via `Facade.Configuration.GrabConfiguration.PrimaryAction.ObjectFollower.TargetOffsets[0]` i think

**Comment by fight4dream** [comment]
confirmed it works

**Comment by thestonefox** [comment]
I've added this fix to this PR:
https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/pull/132
