### ISSUE TITLE
Alternative ways to set up orientation handles for multiple interactors

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#131]
## Is your feature request related to a problem?

The current way is through the GameObjectRelations component. Basically it is like a GameObject rule that map from interactor’s game object to the orientation handle. But it is not flexible when dealing with interactable objects (prefabs) that is instantiated or when the interactors are not initially in the same scene. 

## Describe the solution you'd like

We shall be able to use rules such as AnyTagRule or AnyTypeRule to identify the mapping. That will work for instanced objects as well as interactors.

**Comment by thestonefox** [comment]
can you raise this as a bug with steps to reproduce as it seems there is an issue where you cannot do this if the objects aren't already in the scene

**Comment by fight4dream** [comment]
https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/tree/master/Documentation/HowToGuides/SettingTheOrientationOfAnInteractableWhenGrabbed

follow the guide up to step 7 where we are
asked to drag in the corresponding Interactors. but if the sword is made into a prefab waiting to be instantiated. there is no Interactors that can readily be dragged. 
the interactors are needed to be found in runtime

**Comment by thestonefox** [comment]
So this is possible to do with the Rules Matcher, but having a base generic way of it working may be a bit tricky.

I'm not sure if its best to provide a rules matcher way in the prefab with an option to toggle it, or provide a guide on how to set it up

rough guide is:

* Create the 2 orientation handle gameobjects (for left and right)

* Create a rule that determines left controller (e.g any tag rule)

![image](https://user-images.githubusercontent.com/1029673/177279730-6fe4c0de-ed4b-48e7-a34e-10f07b277726.png)

* Create a rule that determines right controller (e.g any tag rule)

![image](https://user-images.githubusercontent.com/1029673/177279793-163e90c0-f87e-41f9-a97f-a02f447937da.png)

* Create a rules matcher (within the interactable most likely) that is matching for that left/right controller rule

![image](https://user-images.githubusercontent.com/1029673/177280004-ca318ac0-af95-4770-b8a8-2d1917c32ce6.png)

The `Matched()` events for each rule element then sets the `TargetOffsets` element to the manually provided orientation handle.

* Finally, in the `Interactable -> Internal -> GrabLogic -> ActionContainer -> GrabAction.Follow -> Processes -> GrabProcess -> SetupFollow -> GameObjectEventProxyEmitter` - Change the middle event (`OrientationHandles->GameObjectRelations.DoGetValue)`

![image](https://user-images.githubusercontent.com/1029673/177280472-23dde337-f4d1-431a-9604-01e2f263f5a0.png)

to the newly created Rules Matcher `Match` method:

![image](https://user-images.githubusercontent.com/1029673/177280610-5d8e3b65-4d27-40ab-be6f-185314017135.png)


This will then call the rules matcher on setup follow, which will in turn match the correct controller based on a rule and therefore set the correct orientation handle at runtime.

**Comment by thestonefox** [comment]
I've added a feature to this PR:

https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/pull/132
