### ISSUE TITLE
Primary action type None is not triggering any Grabbing events

### ISSUE THREAD

**Issue by Maciej92Zareba** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#136]
Unity 2021.3.4f1
Tilia packages:
![obraz](https://user-images.githubusercontent.com/46682105/189603832-255d6242-1f8c-43e8-b647-585fe7085e29.png)

### Re production steps

Set primary action on interactable to None
![obraz](https://user-images.githubusercontent.com/46682105/189603698-41b762f8-7733-428c-90d8-db221a40515a.png)
Try grab interactable

### Expected behavior

Grab, Ungrab, Touch, Untouch events trigger

### Current behavior

Grab, Ungrab, Touch, Untouch events do not trigger

**Comment by thestonefox** [comment]
This has been fixed.

Touch/Untouch will always raise with `None` action, but Grab/Ungrab will not raise by default as you're not able to grab.

However, if you _need_ that functionality then you can go to the `Grab Interactable Null Action` component within the Interactable hierarchy and tick the `Force Emit Events` property.

![image](https://user-images.githubusercontent.com/1029673/218416740-a3f84514-7323-407a-ba6c-e0adfcb9b861.png)
