### ISSUE TITLE
Toggle mode may not release the interactable

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#42]
### Environment

* Code source: github
* Code version: 59d9ecf
* Platform version: Unity 2019.4.1f1
* 3rd party dependencies:

### Steps to reproduce

1. create a cube of size (0.1, 0.1, 0.1)
2. convert it into interactable
3. set GrabType = Toggle
4. set GrabOffset = Orientation Handle
5. select GenericOrientationHandle and move it to (0.1, 0, 0)
6. press once to grab with right controller
7. press again attempt to release

### Expected behavior

the cube should be released.

### Current behavior

the cube is not released.

### Remark

it seems that the interactor collider is not in touch with the cube collider, so the 'release action' is not triggered. however, if GrabType = Hold Till Release, the cube is released even though the colliders are not touching. Hence, it should behave the same for GrabType = Toggle

**Comment by fight4dream** [comment]
Also, Action Publisher/Receiver does not work in **neither** Hold till release nor Toggle if colliders do not touch

**Comment by thestonefox** [comment]
The issue (in all these cases) is the _touch_ action fills up the ActiveCollisionPublisher of the StartGrabbing (and Action Publisher)

When you no longer touch something it then populates the active collisions with nothing so it doesn't know where to send the events to.

Now if you're already grabbing something and you stop touching it then you should still be able to intrinsically know these items need publishing to.

One potential solution would be to have on the ActiveCollisionPublisher some way of knowing about stored collisions (along with the active collisions taken from the `Payload.ActiveCollisions`)

This stored collision collection would need to be populated by the Grab event (which is passed via the Interactable) and then the ActiveCollisionPublisher would also publish to this stored collection as well (but only if the active collision collection didn't already publish to it)

Then on the Ungrab event, the item being ungrabbed would want to be removed from this store collision data.

This same concept could probably work with the ActionPublisher too.

**Comment by thestonefox** [comment]
If the ActiveCollisionPublisher kept a `GameObjectObservableList` of all registered consumers (i.e. things it has published to in the past)

then this could be set/unset via the grab/ungrab event and there could be an extra option to also publish to registered consumers (if they haven't already been published to in the active consumer list)

**Comment by extendreality** [comment]
Fixed with https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/pull/48
