### ISSUE TITLE
Ability to force snap the orientation of a followed grab to match the interactor

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#46]
Sometimes with certain follow mechanics (such as rigidbody follow) it will diverge too much away from the interactor (e.g. after teleport) and then the interactable is flung with massive force to catch up with the interactor.

There needs to be a way to snap the interactable to the interactor (but it must also be possible to call from the interactor side too)

**Comment by extendreality** [comment]
Fixed with https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/pull/48
