### ISSUE TITLE
Two handed objects in snapzones.

### ISSUE THREAD

**Issue by DonaldPlump** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#55]
### Environment

* Code source: github
* Code version: as this issue might pertain to multiple I've included a screenshot of my tilia packages, the most relevant ones being (snapzone 1.1.19) and (interactables 1.13.3) 
![](https://i.imgur.com/duuNKeV.png)
* Platform version: unity 2019.1.14f1
* 3rd party dependencies: see above

### Steps to reproduce

> 1.  Setup a scene with interactors, an interactable and a snap zone. 
> 2.  Change the interactable action settings, (none for primary) and (custom for secondary)
> 3.  Dig down into the hierarchy of the interactable and into grab logic to set up the secondary action.
> 4.  Add the follow action prefab into the secondary action.
> 5.  In the follow action object change the tracking to follow rigidbody and offset to precision point. 
> 6.  Start the scene, grab the interactable and see that both hands are grabbing for it to be picked up.
> 7.  Drop the interactable outside the snapzone to see that it falls if you release the grab with either hand. 
> 8.  Pick the interactable back up but this time drop it in the snapzone and witness it not snapping to the snapzone. 

### Expected behavior

When releasing the held interactable it should snap to the snapzone like other objects do once I let go of them.

### Current behavior

It displays the highlight once the interactable is inside the activation area, but when it is let go it only drops and doesnt snap. The highlight area still stays on and I am able to pick up other objects.

**Comment by extendreality** [comment]
Fixed in https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/pull/54
