### ISSUE TITLE
Interactor Grab Attach Point can't be moved if using Precision grab

### ISSUE THREAD

**Issue by SmartCarrion** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#66]
### Environment

* Code source: Git
* Code version: 1.15.2
* Platform version: Unity 2019.4.16f1
* 3rd party dependencies: none

### Steps to reproduce

Create a basic Tilia setup with interactors, and an interactable set to Precision Point grab.  Move the Grab Attach Point of one interactor (like your Left Hand interactor) to a slight offset, like (0.1, 0.1, 0.1).  Press play and grab an object with that hand, the item will shift in space by that offset instead of just being precisely grabbed.

### Expected behavior

The item picks up and stays in place relative to your hand. 

### Current behavior

The item is grabbed precisely, but the offset distance is added to its location, so it shifts in an ugly way.

**Comment by thestonefox** [comment]
Yeah I agree the offset shouldn't be applied on precision grab

**Comment by SmartCarrion** [comment]
Glad I could help, hope its an easy fix.  Thanks for all you do on this project!

**Comment by thestonefox** [comment]
fixed with https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/pull/67
