### ISSUE TITLE
Framerate drop when touching/grabbing interactable with multiple children

### ISSUE THREAD

**Issue by Scraphead** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#75]
### Environment

Unity 2019.4.21f
"io.extendreality.tilia.interactions.interactables.unity": "1.15.8",

### Steps to reproduce
1. Create a new unity scene set up with tracked alias and an interactor with grab support.
2. Create an interactable with grab action follow and secondary swap.
3. Set intearactable rigidbody "Is Kinematic" to true.
3. Duplicate interactable and make it as a child of first interactable.
4. Move duplicated interatable a bit away in scene so it does not overlap first interactable.
5. Duplicate the duplicated interactable multiple times so first interactable has about 50 duplicated children.
6. Start game in vr and see framerate drop significantly when touching/grabbing first interactable

Example gif:
![TiliaMultipleChildrenFramerateDrop](https://user-images.githubusercontent.com/1405377/109400970-19aa5200-794c-11eb-8b36-f481589a4777.gif)

### Expected behavior

Touching/Grabbing an interactable with multiple children should maintain decent framerate.

### Current behavior

Touching/Grabbing an interactable with multiple children lowers framerate significantly.

**Comment by thestonefox** [comment]
I don't think it is reasonable to expect this setup to maintain a decent framerate, because of the amount of calls it has to do to check. It's going to be inefficient to do it this way because every interactable will need to communicate with the interactor.

**Comment by Scraphead** [comment]
> 
> 
> I don't think it is reasonable to expect this setup to maintain a decent framerate, because of the amount of calls it has to do to check. It's going to be inefficient to do it this way because every interactable will need to communicate with the interactor.

The given example is exaggerated, but I was inspired by how things was set up in the old farm VRTK prefab project, where the shotgun is made of multiple interactable children. It was appealing to make complex contraptions that way.

If its unfeasible to get it performant by directly attach multiple children, then I think I can solve it by attaching children to a proxy object follower. The interactor then avoids searching a large hierarchy when grabbing "parent" interactable.
I assume this is a good solution, unless there is a better alternative in Tilia.

I assume there will be other crazy users like me attempting to construct larger contraptions. :D

**Comment by thestonefox** [comment]
What are you trying to achieve? If you outline what you're trying to do, then there may be a solution.

The way the shotgun works is by ensuring child interactables block passing messages up to their parents. which would essentially reduce the issue in this report, but it may or may not be what you're trying to achieve.

**Comment by Scraphead** [comment]
In my case, I have a large 7x4 grid of smaller snap zones parented to a moveable plate. I wanted to snap objects to different slots in the grid. Without snapping anything I noticed the fps drop when grabbing the plate. In unity profiler it showed the slowdown was from the interactor calling GetComponentInChildren (If I remember it right).

The given example is just using multiple interactable children, but the framerate drops with multiple snapzone children, (and I assume same thing happens angular/linear drives tool)

If I have misunderstood how it all works, and there is some passing messages I need to block, I will absolutely use that.

**Comment by thestonefox** [comment]
Instead of putting your snap zones as children of an interactable, you could try using the object follower to get the snap zones to follow the interactable and then there shouldn't be any nested messages being passed around

**Comment by Scraphead** [comment]
Sounds good to me. Then I can live in the comfort of knowing the right way to do it.
