### ISSUE TITLE
Secondary action scale is slow to follow interactor's motion.

### ISSUE THREAD

**Issue by Scraphead** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#79]
### Environment

Unity 2019.4.21f
"io.extendreality.tilia.interactions.interactables.unity": "1.15.10",

### Steps to reproduce
1. Create a new unity scene set up with tracked alias.
2. Make an interactable with primary action follow (grab offset set to precision point).
3. Make Secondary action scale.
4. Start game in vr.
5. Grab interactable cube with both hands close to center of one of its faces.
6. Attempt to scale cube up.

Example gif:
![ExpectedPinchScaler](https://user-images.githubusercontent.com/1405377/110245505-b4fe8100-7f63-11eb-8194-f71554154d7c.gif)

### Expected behavior

Cube should quickly scale up due to relative distance of interactors.

### Current behavior

Cube scales up very slowly.

### Other
Changes I made for gif in PinchScaler.cs
<details>
  <summary>Expand code:</summary>
  
  ```cs
    protected virtual void Scale()
    {
        previousDistance = previousDistance == null ? GetDistance() : previousDistance;

        if (previousDistance == 0)
        {
            previousDistance = GetDistance();
            return;
        }
        
        float scaleDelta = Mathf.Pow(GetDistance() / (float) previousDistance, Multiplier);
        Vector3 scaleVector = Vector3.one * scaleDelta;
        if (UseLocalScale)
        {
            Target.transform.localScale = Vector3.Scale(Target.transform.localScale, scaleVector);
        }
        else
        {
            Target.transform.SetGlobalScale(Vector3.Scale(Target.transform.lossyScale, scaleVector));
        }

        previousDistance = GetDistance();
    }
  ```
</details>

**Comment by thestonefox** [comment]
So what's your change here? to get the delta using `Mathf.Pow`?

The original concept was you change your `multiplier` to determine how fast you want the scaling to occur, but does your fix allow for it to work as expected in all cases?

**Comment by Scraphead** [comment]
> So what's your change here? to get the delta using `Mathf.Pow`?

Mathf.Pow is to calculate multiplier, not for initial delta between point.

The ratio is found by dividing new distance with old distance
float scaleRatio = GetDistance() / (float) previousDistance;

(I think ratio is a better term then delta when we talk about scaling)

> The original concept was you change your `multiplier` to determine how fast you want the scaling to occur, but does your fix allow for it to work as expected in all cases?

My napkin math seems to work with multiplier in a Pow operation.
When you scale down, you always end up with a ratio between 0 and 1.
When scaling up, the multiplier behaves in a reasonable manner.

But multiplier should be named exponent in my code.
I might try to figure out the math so it behaves like an multiplier, and not like exponent.
(I think this is easy, but I am too tired now, and I have forgotten way too much math in the years since school xD)

I have commented my changes with some examples.

```diff
        protected virtual void Scale()
        {
             previousDistance = previousDistance == null ? GetDistance() : previousDistance;

+            // Avoids divide by zero if PrimaryPoint and SecondaryPoint is in the same location
+            if (previousDistance == 0)
+            {
+                previousDistance = GetDistance();
+                return;
+            }

+            // Lets pretend we shrink the distance between PrimaryPoint and SecondaryPoint with 25%,
+            // so we want the object we scale to be 25% smaller.
+            //
+            // Example values:
+            // New distance is 0.6
+            // Old distance is 0.8
+            // 0.6/0.8 = 0.75
+            // So we want our new transform scale to be 75% of current size
+            float scaleRatio = GetDistance() / (float) previousDistance;
-            float distanceDelta = GetDistance() - (float)previousDistance;

+            // We stack scaleRatio with multiplier by using pow
+            //
+            // Example values:
+            // Multiplier is 3, so we expect all operations to be trice the scale.
+            //
+            // Since we want the transform scale to apply 75% "trice" we multiply scaleRatio with itself.
+            // 0.75 * 0.75 * 0.75 = 0.421875
+            //
+            // This is equal to the pow operation
+            // Mathf.Pow(0.75, 3) = 0.421875
+            //
+            // Final transform scale is 42.1875% of original size
+            Vector3 scaleVector = Vector3.one * Mathf.Pow(scaleRatio, Multiplier);
-            Vector3 newScale = Vector3.one * distanceDelta * Multiplier;

+            // All math also works when scaling up.
+            // Lets say we double the distance between PrimaryPoint and SecondaryPoint
+            // New distance is 0.4
+            // Old distance is 0.2
+            // scaleRatio = 0.4/0.2 = 2 (200%)
+            //
+            // If multipler is 1 there is no change in scaleRatio
+            // 200%^1 = 200% scale transform
+            //
+            // If multipler is 2 we double the scaleRatio
+            // 200%^2 = 400% scale transform
+            //
+            // If multipler is 3 we have a cubing scaling
+            // 200%^3 = 800% scale transform

             if (UseLocalScale)
             {
+                // Replace localScale by multiplying old scale with scalevector
+                Target.transform.localScale = Vector3.Scale(Target.transform.localScale, scaleVector);
-                Target.transform.localScale += newScale;
             }
             else
             {
+                // Replace lossyScale by multiplying old scale with scalevector
+                Target.transform.SetGlobalScale(Vector3.Scale(Target.transform.lossyScale, scaleVector));
-                Target.transform.SetGlobalScale(Target.transform.lossyScale + newScale);
             }

```

The only edge case I can see is if multiplier is stupid large (close to Single.MaxValue), you get a divide by zero from since Pow operation returns 0.

**Comment by thestonefox** [comment]
Fixed in latest version
